CREATE TABLE [dbo].[Location]
(
	[_Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [_CreatedBy] UNIQUEIDENTIFIER NOT NULL, 
    [_Created] DATETIME NOT NULL, 
    [_Updated] DATETIME NOT NULL, 
    [_UpdatedBy] UNIQUEIDENTIFIER NOT NULL, 
    [_Active] BIT NOT NULL, 
    [_Tags] NVARCHAR(MAX) NULL, 
    [_Comments] NVARCHAR(MAX) NULL, 
    [AddressLine1] NVARCHAR(200) NOT NULL, 
    [AddressLine2] NVARCHAR(200) NULL, 
    [LocalityName] NVARCHAR(200) NULL, 
    [Landmarks] NVARCHAR(200) NULL, 
    [PinCode] NVARCHAR(20) NOT NULL, 
    [MapCordinates] NVARCHAR(50) NULL, 
    [CountryId] UNIQUEIDENTIFIER NOT NULL, 
    [RegionId] UNIQUEIDENTIFIER NOT NULL, 
    [CityId] UNIQUEIDENTIFIER NOT NULL, 
    CONSTRAINT [FK_Location_ToCreatedBy] FOREIGN KEY ([_CreatedBy]) REFERENCES [User]([_Id]), 
    CONSTRAINT [FK_Location_ToUpdatedBy] FOREIGN KEY ([_UpdatedBy]) REFERENCES [User]([_Id]), 
    CONSTRAINT [FK_Location_ToCity] FOREIGN KEY ([CityId]) REFERENCES [City]([_Id]), 
    CONSTRAINT [FK_Location_ToRegion] FOREIGN KEY ([RegionId]) REFERENCES [Region]([_Id]), 
    CONSTRAINT [FK_Location_ToCountry] FOREIGN KEY ([CountryId]) REFERENCES [Country]([_Id])
)
